name: user_repository
description: The Repo that handles the user data
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true